language: python

matrix:
  include:
    - os: linux
      dist: trusty
      python: 3.6
    - os: osx
      osx_image: xcode8.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then  brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  sudo apt-get install -y xvfb build-essential check libpulse-dev libsamplerate0-dev libsndfile1-dev libwavpack-dev libzip-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then  brew install check pulseaudio libsamplerate libsndfile wavpack libzip; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then  brew upgrade python; alias pip=pip3; fi  # https://github.com/travis-ci/travis-ci/issues/2312
  - gcc --version
  - clang --version
  - python3 --version
  - pip3 --version
install:
  - pip3 install pylint flake8 pyqt5
script:
  - ./test_runner.sh
